services:
  tutto_xhtml.renderer:
    class: Tutto\Bundle\XhtmlBundle\Logic\XhtmlRenderer

  tutto_xhtml.twig.renderer:
    class: Tutto\Bundle\XhtmlBundle\Twig\XhtmlRendererExtension
    arguments: ["@tutto_xhtml.renderer"]
    tags:
      - { name: twig.extension }